// ILSpyBased#2
public enum FUFPSOpCode : byte
{
    MasterLobbyJoined = 0xFF,
    BattleMessage = 156,
    Chat = 155,
    JoinRoomSettings = 107,
    ActorLeft = 106,
    ActorJoined = 105,
    Disconnected = 104,
    GameJoined = 103,
    LobbyJoined = 102,
    Connected = 101,
    SpawnRequest = 100,
    Move = 99,
    ChangeWeapon = 98,
    Shot = 97,
    ReloadWeapon = 96,
    KillPlayer = 95,
    SpawnItem = 94,
    PickItem = 93,
    TimeOver = 92,
    NewGame = 91,
    UpdateScore = 90,
    UpdateFlag = 89,
    UpdateControlPoint = 88,
    Enhancer = 87,
    UpdateRoomList = 86,
    UpdatePlayerEnergy = 85,
    GameStateRequest = 84,
    ServerActorCount = 83,
    ServerConnectionError = 82,
    CampaignEvent = 81,
    NotificationEvent = 80,
    BaseEnter = 79,
    EscortMachineEvent = 78,
    AnimationEvent = 77,
    Achievement = 76,
    UserCloneAlert = 75,
    Impact = 74,
    UpdateZombie = 73,
    Synchronize = 72,
    Console = 71,
    Kick = 70,
    PlayerDataReady = 67
}


