// ILSpyBased#2
public enum GameHUDMessageType : byte
{
    EMPTY_FLAG_POINT = 1,
    FLAG_CAPTURED,
    FLAG_YOU_CAPTURED,
    FLAG_ENEMY_CAPTURED,
    FLAG_DELIVERED,
    FLAG_YOU_DELIVERED,
    FLAG_ENEMY_DELIVERED,
    FLAG_LOST,
    FLAG_ENEMY_LOST,
    FLAG_RETURNED,
    FLAG_YOU_RETURNED,
    FLAG_ENEMY_RETURNED,
    TOWER_CORE_ATTACK = 21,
    TOWER_NEW_WAVE,
    TOWER_FINISH_WAVE,
    ZOMBIE_WAITING_PLAYERS,
    ZOMBIE_BOSS_INFECTION,
    ZOMBIE_DEAD_PLAYER,
    ZOMBIE_DEAD_ZOMBIE
}


