// ILSpyBased#2
public enum NotificationType : byte
{
    None,
    ActivityIdle = 99,
    PingOverhead = 98,
    MoveCheatingOld = 97,
    TimeCheatingOld = 96,
    WallCheating = 3,
    FlyCheating,
    SpeedCheating,
    GravityCheating,
    DeviationCheating,
    RapidityCheating,
    GatesCheating,
    NetworkCheating,
    ShotTimeCheating,
    MoveCheating,
    ShiftCheating,
    TimeCheating,
    WallCheatingServer,
    WallCheatingSpectator,
    WallHackCheating,
    FlyJumpStartTime,
    FlyJumpStartTimeHacker,
    EventCheating,
    TransformCheating,
    FallingUp,
    Synchronization,
    AntiKickCheating,
    ErrorCheating,
    WallShotCheating,
    WallShotThroughCheating,
    NicknameCheating,
    UnderfloorCheating,
    BugResponse,
    NetworkErrorCheating,
    PositionCheating,
    WeaponSwitchCheating,
    FastAimCheating,
    JumpMaxCheating,
    WallShotThroughServerCheating
}


