// ILSpyBased#2
public enum WeaponType : byte
{
    NONE,
    ONE_HANDED_COLD_ARMS,
    TWO_HANDED_COLD_ARMS,
    HAND_GUN,
    MACHINE_GUN,
    FLAMER,
    GATLING_GUN,
    SHOT_GUN,
    ROCKET_LAUNCHER,
    GRENADE_LAUNCHER,
    SNIPER_RIFLE,
    SNOW_GUN,
    ACID_THROWER,
    ELECTRO_SHOCKER,
    BIO_SHOCKER,
    BOMB_LAUNCHER,
    MINE_SPIDER = 101,
    TURRET_MACHINE_GUN,
    MINE_ELECTRIC_REMOTE,
    MINE_TIME,
    MINE_TOUCH,
    MINE_REMOTE,
    MINE_ELECTRIC,
    TURRET_TESLA,
    CHARGER = 201,
    MEGA_CHARGER,
    KAMIKADZE
}


